# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dot2snap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protocol_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dot2snap.proto',
  package='OstProto',
  serialized_pb=_b('\n\x0e\x64ot2snap.proto\x12\x08OstProto\x1a\x0eprotocol.proto\"\n\n\x08\x44ot2Snap:9\n\x08\x64ot2Snap\x12\x12.OstProto.Protocol\x18\xcf\x01 \x01(\x0b\x32\x12.OstProto.Dot2Snap')
  ,
  dependencies=[protocol_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DOT2SNAP_FIELD_NUMBER = 207
dot2Snap = _descriptor.FieldDescriptor(
  name='dot2Snap', full_name='OstProto.dot2Snap', index=0,
  number=207, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_DOT2SNAP = _descriptor.Descriptor(
  name='Dot2Snap',
  full_name='OstProto.Dot2Snap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=54,
)

DESCRIPTOR.message_types_by_name['Dot2Snap'] = _DOT2SNAP
DESCRIPTOR.extensions_by_name['dot2Snap'] = dot2Snap

Dot2Snap = _reflection.GeneratedProtocolMessageType('Dot2Snap', (_message.Message,), dict(
  DESCRIPTOR = _DOT2SNAP,
  __module__ = 'dot2snap_pb2'
  # @@protoc_insertion_point(class_scope:OstProto.Dot2Snap)
  ))
_sym_db.RegisterMessage(Dot2Snap)

dot2Snap.message_type = _DOT2SNAP
protocol_pb2.Protocol.RegisterExtension(dot2Snap)

# @@protoc_insertion_point(module_scope)
