# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dot2llc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protocol_pb2
import dot3_pb2
import llc_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dot2llc.proto',
  package='OstProto',
  serialized_pb=_b('\n\rdot2llc.proto\x12\x08OstProto\x1a\x0eprotocol.proto\x1a\ndot3.proto\x1a\tllc.proto\"\t\n\x07\x44ot2Llc:7\n\x07\x64ot2Llc\x12\x12.OstProto.Protocol\x18\xce\x01 \x01(\x0b\x32\x11.OstProto.Dot2Llc')
  ,
  dependencies=[protocol_pb2.DESCRIPTOR,dot3_pb2.DESCRIPTOR,llc_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DOT2LLC_FIELD_NUMBER = 206
dot2Llc = _descriptor.FieldDescriptor(
  name='dot2Llc', full_name='OstProto.dot2Llc', index=0,
  number=206, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_DOT2LLC = _descriptor.Descriptor(
  name='Dot2Llc',
  full_name='OstProto.Dot2Llc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['Dot2Llc'] = _DOT2LLC
DESCRIPTOR.extensions_by_name['dot2Llc'] = dot2Llc

Dot2Llc = _reflection.GeneratedProtocolMessageType('Dot2Llc', (_message.Message,), dict(
  DESCRIPTOR = _DOT2LLC,
  __module__ = 'dot2llc_pb2'
  # @@protoc_insertion_point(class_scope:OstProto.Dot2Llc)
  ))
_sym_db.RegisterMessage(Dot2Llc)

dot2Llc.message_type = _DOT2LLC
protocol_pb2.Protocol.RegisterExtension(dot2Llc)

# @@protoc_insertion_point(module_scope)
