# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dot3.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protocol_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dot3.proto',
  package='OstProto',
  serialized_pb=_b('\n\ndot3.proto\x12\x08OstProto\x1a\x0eprotocol.proto\"2\n\x04\x44ot3\x12\x1a\n\x12is_override_length\x18\x02 \x01(\x08\x12\x0e\n\x06length\x18\x01 \x01(\r:1\n\x04\x64ot3\x12\x12.OstProto.Protocol\x18\xc9\x01 \x01(\x0b\x32\x0e.OstProto.Dot3')
  ,
  dependencies=[protocol_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DOT3_FIELD_NUMBER = 201
dot3 = _descriptor.FieldDescriptor(
  name='dot3', full_name='OstProto.dot3', index=0,
  number=201, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_DOT3 = _descriptor.Descriptor(
  name='Dot3',
  full_name='OstProto.Dot3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_override_length', full_name='OstProto.Dot3.is_override_length', index=0,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='OstProto.Dot3.length', index=1,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['Dot3'] = _DOT3
DESCRIPTOR.extensions_by_name['dot3'] = dot3

Dot3 = _reflection.GeneratedProtocolMessageType('Dot3', (_message.Message,), dict(
  DESCRIPTOR = _DOT3,
  __module__ = 'dot3_pb2'
  # @@protoc_insertion_point(class_scope:OstProto.Dot3)
  ))
_sym_db.RegisterMessage(Dot3)

dot3.message_type = _DOT3
protocol_pb2.Protocol.RegisterExtension(dot3)

# @@protoc_insertion_point(module_scope)
