# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eth2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protocol_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='eth2.proto',
  package='OstProto',
  serialized_pb=_b('\n\neth2.proto\x12\x08OstProto\x1a\x0eprotocol.proto\".\n\x04\x45th2\x12\x18\n\x10is_override_type\x18\x02 \x01(\x08\x12\x0c\n\x04type\x18\x01 \x01(\r:1\n\x04\x65th2\x12\x12.OstProto.Protocol\x18\xc8\x01 \x01(\x0b\x32\x0e.OstProto.Eth2')
  ,
  dependencies=[protocol_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


ETH2_FIELD_NUMBER = 200
eth2 = _descriptor.FieldDescriptor(
  name='eth2', full_name='OstProto.eth2', index=0,
  number=200, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_ETH2 = _descriptor.Descriptor(
  name='Eth2',
  full_name='OstProto.Eth2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_override_type', full_name='OstProto.Eth2.is_override_type', index=0,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='OstProto.Eth2.type', index=1,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['Eth2'] = _ETH2
DESCRIPTOR.extensions_by_name['eth2'] = eth2

Eth2 = _reflection.GeneratedProtocolMessageType('Eth2', (_message.Message,), dict(
  DESCRIPTOR = _ETH2,
  __module__ = 'eth2_pb2'
  # @@protoc_insertion_point(class_scope:OstProto.Eth2)
  ))
_sym_db.RegisterMessage(Eth2)

eth2.message_type = _ETH2
protocol_pb2.Protocol.RegisterExtension(eth2)

# @@protoc_insertion_point(module_scope)
