# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ip6over4.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protocol_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ip6over4.proto',
  package='OstProto',
  serialized_pb=_b('\n\x0eip6over4.proto\x12\x08OstProto\x1a\x0eprotocol.proto\"\n\n\x08Ip6over4:9\n\x08ip6over4\x12\x12.OstProto.Protocol\x18\xaf\x02 \x01(\x0b\x32\x12.OstProto.Ip6over4')
  ,
  dependencies=[protocol_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


IP6OVER4_FIELD_NUMBER = 303
ip6over4 = _descriptor.FieldDescriptor(
  name='ip6over4', full_name='OstProto.ip6over4', index=0,
  number=303, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_IP6OVER4 = _descriptor.Descriptor(
  name='Ip6over4',
  full_name='OstProto.Ip6over4',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=54,
)

DESCRIPTOR.message_types_by_name['Ip6over4'] = _IP6OVER4
DESCRIPTOR.extensions_by_name['ip6over4'] = ip6over4

Ip6over4 = _reflection.GeneratedProtocolMessageType('Ip6over4', (_message.Message,), dict(
  DESCRIPTOR = _IP6OVER4,
  __module__ = 'ip6over4_pb2'
  # @@protoc_insertion_point(class_scope:OstProto.Ip6over4)
  ))
_sym_db.RegisterMessage(Ip6over4)

ip6over4.message_type = _IP6OVER4
protocol_pb2.Protocol.RegisterExtension(ip6over4)

# @@protoc_insertion_point(module_scope)
