# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protocol_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='llc.proto',
  package='OstProto',
  serialized_pb=_b('\n\tllc.proto\x12\x08OstProto\x1a\x0eprotocol.proto\"{\n\x03Llc\x12\x18\n\x10is_override_dsap\x18\x04 \x01(\x08\x12\x18\n\x10is_override_ssap\x18\x05 \x01(\x08\x12\x17\n\x0fis_override_ctl\x18\x06 \x01(\x08\x12\x0c\n\x04\x64sap\x18\x01 \x01(\r\x12\x0c\n\x04ssap\x18\x02 \x01(\r\x12\x0b\n\x03\x63tl\x18\x03 \x01(\r:/\n\x03llc\x12\x12.OstProto.Protocol\x18\xca\x01 \x01(\x0b\x32\r.OstProto.Llc')
  ,
  dependencies=[protocol_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


LLC_FIELD_NUMBER = 202
llc = _descriptor.FieldDescriptor(
  name='llc', full_name='OstProto.llc', index=0,
  number=202, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_LLC = _descriptor.Descriptor(
  name='Llc',
  full_name='OstProto.Llc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_override_dsap', full_name='OstProto.Llc.is_override_dsap', index=0,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_override_ssap', full_name='OstProto.Llc.is_override_ssap', index=1,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_override_ctl', full_name='OstProto.Llc.is_override_ctl', index=2,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dsap', full_name='OstProto.Llc.dsap', index=3,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ssap', full_name='OstProto.Llc.ssap', index=4,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ctl', full_name='OstProto.Llc.ctl', index=5,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['Llc'] = _LLC
DESCRIPTOR.extensions_by_name['llc'] = llc

Llc = _reflection.GeneratedProtocolMessageType('Llc', (_message.Message,), dict(
  DESCRIPTOR = _LLC,
  __module__ = 'llc_pb2'
  # @@protoc_insertion_point(class_scope:OstProto.Llc)
  ))
_sym_db.RegisterMessage(Llc)

llc.message_type = _LLC
protocol_pb2.Protocol.RegisterExtension(llc)

# @@protoc_insertion_point(module_scope)
