# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mac.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protocol_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mac.proto',
  package='OstProto',
  serialized_pb=_b('\n\tmac.proto\x12\x08OstProto\x1a\x0eprotocol.proto\"\xd6\x02\n\x03Mac\x12\x0f\n\x07\x64st_mac\x18\x01 \x01(\x04\x12;\n\x0c\x64st_mac_mode\x18\x02 \x01(\x0e\x32\x19.OstProto.Mac.MacAddrMode:\ne_mm_fixed\x12\x19\n\rdst_mac_count\x18\x03 \x01(\r:\x02\x31\x36\x12\x17\n\x0c\x64st_mac_step\x18\x04 \x01(\r:\x01\x31\x12\x0f\n\x07src_mac\x18\x05 \x01(\x04\x12;\n\x0csrc_mac_mode\x18\x06 \x01(\x0e\x32\x19.OstProto.Mac.MacAddrMode:\ne_mm_fixed\x12\x19\n\rsrc_mac_count\x18\x07 \x01(\r:\x02\x31\x36\x12\x17\n\x0csrc_mac_step\x18\x08 \x01(\r:\x01\x31\"K\n\x0bMacAddrMode\x12\x0e\n\ne_mm_fixed\x10\x00\x12\x0c\n\x08\x65_mm_inc\x10\x01\x12\x0c\n\x08\x65_mm_dec\x10\x02\x12\x10\n\x0c\x65_mm_resolve\x10\x03:.\n\x03mac\x12\x12.OstProto.Protocol\x18\x64 \x01(\x0b\x32\r.OstProto.Mac')
  ,
  dependencies=[protocol_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


MAC_FIELD_NUMBER = 100
mac = _descriptor.FieldDescriptor(
  name='mac', full_name='OstProto.mac', index=0,
  number=100, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

_MAC_MACADDRMODE = _descriptor.EnumDescriptor(
  name='MacAddrMode',
  full_name='OstProto.Mac.MacAddrMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='e_mm_fixed', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='e_mm_inc', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='e_mm_dec', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='e_mm_resolve', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=307,
  serialized_end=382,
)
_sym_db.RegisterEnumDescriptor(_MAC_MACADDRMODE)


_MAC = _descriptor.Descriptor(
  name='Mac',
  full_name='OstProto.Mac',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dst_mac', full_name='OstProto.Mac.dst_mac', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dst_mac_mode', full_name='OstProto.Mac.dst_mac_mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dst_mac_count', full_name='OstProto.Mac.dst_mac_count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=16,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dst_mac_step', full_name='OstProto.Mac.dst_mac_step', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src_mac', full_name='OstProto.Mac.src_mac', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src_mac_mode', full_name='OstProto.Mac.src_mac_mode', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src_mac_count', full_name='OstProto.Mac.src_mac_count', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=16,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src_mac_step', full_name='OstProto.Mac.src_mac_step', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MAC_MACADDRMODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=382,
)

_MAC.fields_by_name['dst_mac_mode'].enum_type = _MAC_MACADDRMODE
_MAC.fields_by_name['src_mac_mode'].enum_type = _MAC_MACADDRMODE
_MAC_MACADDRMODE.containing_type = _MAC
DESCRIPTOR.message_types_by_name['Mac'] = _MAC
DESCRIPTOR.extensions_by_name['mac'] = mac

Mac = _reflection.GeneratedProtocolMessageType('Mac', (_message.Message,), dict(
  DESCRIPTOR = _MAC,
  __module__ = 'mac_pb2'
  # @@protoc_insertion_point(class_scope:OstProto.Mac)
  ))
_sym_db.RegisterMessage(Mac)

mac.message_type = _MAC
protocol_pb2.Protocol.RegisterExtension(mac)

# @@protoc_insertion_point(module_scope)
