# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protocol_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='snap.proto',
  package='OstProto',
  serialized_pb=_b('\n\nsnap.proto\x12\x08OstProto\x1a\x0eprotocol.proto\"T\n\x04Snap\x12\x17\n\x0fis_override_oui\x18\x03 \x01(\x08\x12\x18\n\x10is_override_type\x18\x04 \x01(\x08\x12\x0b\n\x03oui\x18\x01 \x01(\r\x12\x0c\n\x04type\x18\x02 \x01(\r:1\n\x04snap\x12\x12.OstProto.Protocol\x18\xcb\x01 \x01(\x0b\x32\x0e.OstProto.Snap')
  ,
  dependencies=[protocol_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


SNAP_FIELD_NUMBER = 203
snap = _descriptor.FieldDescriptor(
  name='snap', full_name='OstProto.snap', index=0,
  number=203, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_SNAP = _descriptor.Descriptor(
  name='Snap',
  full_name='OstProto.Snap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_override_oui', full_name='OstProto.Snap.is_override_oui', index=0,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_override_type', full_name='OstProto.Snap.is_override_type', index=1,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oui', full_name='OstProto.Snap.oui', index=2,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='OstProto.Snap.type', index=3,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['Snap'] = _SNAP
DESCRIPTOR.extensions_by_name['snap'] = snap

Snap = _reflection.GeneratedProtocolMessageType('Snap', (_message.Message,), dict(
  DESCRIPTOR = _SNAP,
  __module__ = 'snap_pb2'
  # @@protoc_insertion_point(class_scope:OstProto.Snap)
  ))
_sym_db.RegisterMessage(Snap)

snap.message_type = _SNAP
protocol_pb2.Protocol.RegisterExtension(snap)

# @@protoc_insertion_point(module_scope)
