# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protocol_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='stp.proto',
  package='OstProto',
  serialized_pb=_b('\n\tstp.proto\x12\x08OstProto\x1a\x0eprotocol.proto\"\x80\x02\n\x03Stp\x12\x16\n\x0bprotocol_id\x18\x01 \x01(\r:\x01\x30\x12\x1e\n\x13protocol_version_id\x18\x02 \x01(\r:\x01\x30\x12\x14\n\tbpdu_type\x18\x03 \x01(\r:\x01\x30\x12\r\n\x05\x66lags\x18\x04 \x01(\r\x12\x0f\n\x07root_id\x18\x05 \x01(\x04\x12\x16\n\x0eroot_path_cost\x18\x06 \x01(\r\x12\x11\n\tbridge_id\x18\x07 \x01(\x04\x12\x0f\n\x07port_id\x18\x08 \x01(\r\x12\x13\n\x0bmessage_age\x18\t \x01(\r\x12\x0f\n\x07max_age\x18\n \x01(\r\x12\x12\n\nhello_time\x18\x0b \x01(\r\x12\x15\n\rforward_delay\x18\x0c \x01(\r:/\n\x03stp\x12\x12.OstProto.Protocol\x18\xd2\x01 \x01(\x0b\x32\r.OstProto.Stp')
  ,
  dependencies=[protocol_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


STP_FIELD_NUMBER = 210
stp = _descriptor.FieldDescriptor(
  name='stp', full_name='OstProto.stp', index=0,
  number=210, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_STP = _descriptor.Descriptor(
  name='Stp',
  full_name='OstProto.Stp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocol_id', full_name='OstProto.Stp.protocol_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='protocol_version_id', full_name='OstProto.Stp.protocol_version_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bpdu_type', full_name='OstProto.Stp.bpdu_type', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flags', full_name='OstProto.Stp.flags', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='root_id', full_name='OstProto.Stp.root_id', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='root_path_cost', full_name='OstProto.Stp.root_path_cost', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bridge_id', full_name='OstProto.Stp.bridge_id', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port_id', full_name='OstProto.Stp.port_id', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_age', full_name='OstProto.Stp.message_age', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_age', full_name='OstProto.Stp.max_age', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hello_time', full_name='OstProto.Stp.hello_time', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forward_delay', full_name='OstProto.Stp.forward_delay', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=296,
)

DESCRIPTOR.message_types_by_name['Stp'] = _STP
DESCRIPTOR.extensions_by_name['stp'] = stp

Stp = _reflection.GeneratedProtocolMessageType('Stp', (_message.Message,), dict(
  DESCRIPTOR = _STP,
  __module__ = 'stp_pb2'
  # @@protoc_insertion_point(class_scope:OstProto.Stp)
  ))
_sym_db.RegisterMessage(Stp)

stp.message_type = _STP
protocol_pb2.Protocol.RegisterExtension(stp)

# @@protoc_insertion_point(module_scope)
