# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svlan.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protocol_pb2
import vlan_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='svlan.proto',
  package='OstProto',
  serialized_pb=_b('\n\x0bsvlan.proto\x12\x08OstProto\x1a\x0eprotocol.proto\x1a\nvlan.proto:2\n\x05svlan\x12\x12.OstProto.Protocol\x18\xcc\x01 \x01(\x0b\x32\x0e.OstProto.Vlan')
  ,
  dependencies=[protocol_pb2.DESCRIPTOR,vlan_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


SVLAN_FIELD_NUMBER = 204
svlan = _descriptor.FieldDescriptor(
  name='svlan', full_name='OstProto.svlan', index=0,
  number=204, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

DESCRIPTOR.extensions_by_name['svlan'] = svlan

svlan.message_type = vlan_pb2._VLAN
protocol_pb2.Protocol.RegisterExtension(svlan)

# @@protoc_insertion_point(module_scope)
