# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vlan.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protocol_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vlan.proto',
  package='OstProto',
  serialized_pb=_b('\n\nvlan.proto\x12\x08OstProto\x1a\x0eprotocol.proto\"@\n\x04Vlan\x12\x18\n\x10is_override_tpid\x18\x01 \x01(\x08\x12\x0c\n\x04tpid\x18\x02 \x01(\r\x12\x10\n\x08vlan_tag\x18\x03 \x01(\r:1\n\x04vlan\x12\x12.OstProto.Protocol\x18\xcd\x01 \x01(\x0b\x32\x0e.OstProto.Vlan')
  ,
  dependencies=[protocol_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


VLAN_FIELD_NUMBER = 205
vlan = _descriptor.FieldDescriptor(
  name='vlan', full_name='OstProto.vlan', index=0,
  number=205, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_VLAN = _descriptor.Descriptor(
  name='Vlan',
  full_name='OstProto.Vlan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_override_tpid', full_name='OstProto.Vlan.is_override_tpid', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tpid', full_name='OstProto.Vlan.tpid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vlan_tag', full_name='OstProto.Vlan.vlan_tag', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['Vlan'] = _VLAN
DESCRIPTOR.extensions_by_name['vlan'] = vlan

Vlan = _reflection.GeneratedProtocolMessageType('Vlan', (_message.Message,), dict(
  DESCRIPTOR = _VLAN,
  __module__ = 'vlan_pb2'
  # @@protoc_insertion_point(class_scope:OstProto.Vlan)
  ))
_sym_db.RegisterMessage(Vlan)

vlan.message_type = _VLAN
protocol_pb2.Protocol.RegisterExtension(vlan)

# @@protoc_insertion_point(module_scope)
